### ISSUE TITLE
Error in building Sample Application

### ISSUE THREAD

**Issue by subinsebastien** [eamocanu/Facebook.Qt.APIs#2]
I tried to build the sample started code in Qt creator.
Qt version 4.7.3
Qt creator version 2.2.1
Operating System : Ubuntu 11.10
# The Compiler Output:

Running build steps for project facebook...
Starting: "/usr/bin/qmake-qt4" '/home/napster/Downloads/eamocanu-Facebook.Qt.APIs-52578e3/sample 2 starter code/facebook.pro' -r -spec linux-g++
Project MESSAGE: Warning: unknown QT: qtmain
WARNING: Failure to find: FBNetworkRequest.cpp
WARNING: Failure to find: FBUserManager.cpp
WARNING: Failure to find: JSONEvaluator.cpp
WARNING: Failure to find: PhotoData.cpp
WARNING: Failure to find: Facebook.cpp
WARNING: Failure to find: FBNetworkRequest.h
WARNING: Failure to find: FBUserManager.h
WARNING: Failure to find: FBUser.h
WARNING: Failure to find: JSONEvaluator.h
WARNING: Failure to find: PhotoData.h
WARNING: Failure to find: Facebook.h
The process "/usr/bin/qmake-qt4" exited normally.
Starting: "/usr/bin/make" -w
make: Entering directory `/home/napster/Downloads/eamocanu-Facebook.Qt.APIs-52578e3/facebook-build-desktop'
g++ -c -pipe -g -D_REENTRANT -Wall -W -DQT_WEBKIT -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../sample\ 2\ starter\ code -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -I../sample\ 2\ starter\ code -I. -o UIFBUser.o ../sample\ 2\ starter\ code/UIFBUser.cpp
../sample 2 starter code/UIFBUser.cpp: In member function ‘void UIFBUser::setUserName(QString)’:
../sample 2 starter code/UIFBUser.cpp:61:9: warning: variable ‘sz1’ set but not used [-Wunused-but-set-variable]
../sample 2 starter code/UIFBUser.cpp:62:8: warning: variable ‘sz2’ set but not used [-Wunused-but-set-variable]
../sample 2 starter code/UIFBUser.cpp: In member function ‘void UIFBUser::setUserLocation(QString)’:
../sample 2 starter code/UIFBUser.cpp:71:9: warning: variable ‘sz1’ set but not used [-Wunused-but-set-variable]
../sample 2 starter code/UIFBUser.cpp:72:8: warning: variable ‘sz2’ set but not used [-Wunused-but-set-variable]
g++ -c -pipe -g -D_REENTRANT -Wall -W -DQT_WEBKIT -DQT_WEBKIT_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED -I/usr/share/qt4/mkspecs/linux-g++ -I../sample\ 2\ starter\ code -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtNetwork -I/usr/include/qt4/QtGui -I/usr/include/qt4/QtWebKit -I/usr/include/qt4 -I. -I../sample\ 2\ starter\ code -I. -o UIFBmain.o ../sample\ 2\ starter\ code/UIFBmain.cpp
make: *** No rule to make target`FBNetworkRequest.cpp', needed by `FBNetworkRequest.o'.  Stop.
make: Leaving directory`/home/napster/Downloads/eamocanu-Facebook.Qt.APIs-52578e3/facebook-build-desktop'
The process "/usr/bin/make" exited with code 2.
Error while building project facebook (target: Desktop)
When executing build step 'Make'

**Comment by eamocanu** [comment]
Hi!
Please see readme file in the same folder as the sample.

"To run this code, place all files from this folder together with the API files.
Create the .pro file and load into Visual Studio (or another IDE). Run it!

I included a sample .pro file for Windows."

You have to place the sample files together with the API files in the same folder.
