### ISSUE TITLE
After the logg in the programs stops :S

### ISSUE THREAD

**Issue by Evanof** [eamocanu/Facebook.Qt.APIs#3]
Hi Adrian I'm a beginer programer and i'm trying to make something like you did.. i was checking your code and project and first of all: Good Job man! 

but i'm having problems trying to run the project.. everytime that i run it after the first loggin on FB the program stops :S im sending you the image of that...

sorry to ask man,, but could you please help me? i imagine that is the problem is in the token,, is a valid token i've checked that but,, somehow FB is not responding..

**Comment by eamocanu** [comment]
"And yes thanks i'll check their documentation, because this is my main problem i dont know how do you send messages to FB and how FB answer :S (Any suggestion?)"

I'm not sure if you are referring to (1) sending messages to FB on a forums (ie: like asking them for help) or you (2) are asking how to send messages to facebook using this API.

Let me know which one you mean.

Adrian

On Thu, Jan 24, 2013 at 12:25 AM, Ephraim Palma wrote:

```
Thanks man! mmm unfortunately i dont know how to open a bug request :S but if you tell me i'll do it 

And yes thanks i'll check their documentation, because this is my main problem i dont know how do you send messages to FB and how FB answer :S (Any suggestion?)

i'll keep reading the code , Thanks again bro


2013/1/23 Adrian

    Hi
    First, do you by any chance know how to open a bug request on github? Try to do that since others might have the same problem and I can point them there to the solution (ie this conversation).

    In the meanwhile I think the problem is that when you log in the application asks facebook for some permissions via strings (ie: email,wall,etc). I think the error says that FB changed the names of these permission strings. Probably remove them all... maybe keep one like email. FB might have updated their documentation page (?) so you can look at that and

    Adrian
```

**Comment by eamocanu** [comment]
the app talks to FB APIs in

FBNetworkRequest.cpp with 2 methods:
void FBNetworkRequest::createMultipartPostMessageHeader()
void FBNetworkRequest::createMultipartPostMessage(const QByteArray *photoData, const QString &photoCaption)

Oh, and I think the permission problem you mentioned before is with this string:

#define URL "https://graph.facebook.com/oauth/authorize?client_id=%1&redirect_uri=%2&type=user_agent&display=%3&scope=publish_stream,user_photos,read_stream,email"

Everything that is scope is permissions. I'm guessing the names of some may have changed
